### ISSUE TITLE
"Anonymization"

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [con/open-brain-consent#106]
Please do not use the word _Anonymization_. It has a specific and complex definition in the EU under the GDPR. See for example:
* [Opinion 05/2014 on Anonymisation Techniques](https://ec.europa.eu/justice/article-29/documentation/opinion-recommendation/files/2014/wp216_en.pdf)
* [AEPD-EDPS joint paper on 10 misunderstandings related to anonymisation](https://edps.europa.eu/data-protection/our-work/publications/papers/aepd-edps-joint-paper-10-misunderstandings-related_en)

I have found using the term "anonymization" is one of the main sources of misunderstanding between US ans EU researchers.

Instead, use pseudonymization or de-identification depending on the context.

**Comment by DimitriPapadopoulos** [comment]
I can prepare a merge request if you find the suggestion acceptable.

**Comment by CPernet** [comment]
see response on that issue 'de-identification' is HIPPA and that is not at all anonymization as GDPR intended
