### ISSUE TITLE
pseudo-anonymi[sz]ation → pseudononymi[sz]ation

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [con/open-brain-consent#109]
From the very minor details department: I see a mixture of:
* **anonymized** (1 occurrence of the American/Oxford spelling) vs. **anonymised** (2 occurrences of the British spelling)
* **pseudoanonymized** (1 occurrence of American/Oxford spelling and lack of hyphen) vs. **pseudonymised** (1 occurrence of British spelling)

Of course, they are all correct (except perhaps pseudoanonymized) but perhaps we could standardize:
* American/Oxford or British spelling? As a European I'm all for British spelling :-)
* **pseudo-anonymi[sz]ed** or **pseudonymi[sz]ed**? Note that **pseudo-anonymization** is used everywhere else in the document.

**Comment by CPernet** [comment]
we must used 'pseudonymized' which is the GDPR term (the process and pseudo-anonymizaiton)

**Comment by DimitriPapadopoulos** [comment]
I agree we should use _pseudonymi[sz]ed_/_pseudonymi[sz]ation_ everywhere, hence:
* pseudo-anonymi[sz]ed → pseudonymi[sz]ed
* pseudo-anonymi[sz]ation → pseudononymi[sz]ation

But then should we use the usual British spelling _pseudonymised_/_pseudonymisation_ as opposed to the American/Oxford spelling _pseudonymized_/_pseudonymization_? Note that EU documents use British spelling, see for example:
* the GDPR or [Regulation (EU) 2016/679](https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:02016R0679-20160504) itself,
* ENISA [Pseudonymisation techniques and best practices](https://www.enisa.europa.eu/publications/pseudonymisation-techniques-and-best-practices)

As I said, I'm all for British spelling :-)

**Comment by DimitriPapadopoulos** [comment]
Occurrences of all these terms in Google searches, both with British spelling:

**pseudonymisation**: [265000](https://www.google.com/search?q="pseudonymisation")
**pseudo-anonymisation**: [6800](https://www.google.com/search?q="pseudo-anonymisation")
**pseudo anonymisation**: [5570](https://www.google.com/search?q="pseudo%20anonymisation")

**pseudonymise**: [23800](https://www.google.com/search?q="pseudonymise")
**pseudo-anonymise**: [1340](https://www.google.com/search?q="pseudo-anonymise")
**pseudo anonymise**: [1340](https://www.google.com/search?q="pseudo%20anonymise")

and American/Oxford spelling:

**pseudonymization**: [151000](https://www.google.com/search?q="pseudonymization")
**pseudo-anonymization**: [3680](https://www.google.com/search?q="pseudo-anonymization")
**pseudo anonymization**: [3810](https://www.google.com/search?q="pseudo%20anonymization")

**pseudonymize**: [24900](https://www.google.com/search?q="pseudonymize")
**pseudo-anonymize**: [842](https://www.google.com/search?q="pseudo-anonymize")
**pseudo anonymize**: [793](https://www.google.com/search?q="pseudo%20anonymize")

**Comment by CPernet** [comment]
since the term comes from GDPR (I'm quite sure we use to say pseudo-anon) I'm happy with British speling

**Comment by DimitriPapadopoulos** [comment]
I'll just focus on the first issue and leave spelling issues aside.

**Comment by CPernet** [comment]
let's fix the rest (de-id + glossary) and I can do a quick pass for spelling

**Comment by DimitriPapadopoulos** [comment]
@CPernet The glossary is for a different pull request / issue: #108 / #106.It's unrelated to this specific issue.
