### ISSUE TITLE
Link to Hum Brain Mapp. paper?

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [con/open-brain-consent#119]
What about adding a link to [The Open Brain Consent: Informing research participants and obtaining consent to share brain imaging data](https://doi.org/10.1002/hbm.25351) Hum Brain Mapp. paper?

Perhaps under [**History and links**](https://open-brain-consent.readthedocs.io/en/stable/gdpr/index.html#history-and-links)?

**Comment by yarikoptic** [comment]
that one is GDPR specific whenever paper is about entire project. 
May be add "Publications" section with that one above https://open-brain-consent.readthedocs.io/en/stable/index.html#useful-links on the main "page"?

**Comment by DimitriPapadopoulos** [comment]
It appears a link to the post-print is already available in [`docs/source/README.rst`](https://github.com/con/open-brain-consent/blob/master/docs/source/README.rst) under [**Statement of the problem**](https://github.com/con/open-brain-consent/tree/master/docs/source/README.rst#statement-of-the-problem). I have updated it to point the published paper.

Additionally, [`README.md`](https://github.com/con/open-brain-consent/blob/master/README.md) has diverged from [`docs/source/README.rst`](https://github.com/con/open-brain-consent/blob/master/docs/source/README.rst). Among other issues, the above link is missing from [`README.md`](https://github.com/con/open-brain-consent/blob/master/README.md). Shouldn't I sync these files?

Finally, the [stable version published on readthedocs.io](https://open-brain-consent.readthedocs.io/) is not up-to-date and is missing the link. How to update it? Is it sync'ed with [`docs/source/README.rst`](https://github.com/con/open-brain-consent/blob/master/docs/source/README.rst) has diverged from [`README.md`](https://github.com/con/open-brain-consent/blob/master/README.md)?
