### ISSUE TITLE
DUA: This agreement never has prevalence

### ISSUE THREAD

**Issue by DimitriPapadopoulos** [con/open-brain-consent#123]
> 1. I will comply with all relevant rules and regulations imposed by my institution and my government. This agreement never has prevalence over existing general data protection regulations that are applicable in my country.

In the EU, we must strive to have GPRD apply to data originating from the EU, even when exported from the EU. I feel this opens the door to accepting the prevalence of the CLOUD act over the GDPR. Of course local laws and regulations prevail over the agreement, but I think it should go _without saying_.

**Comment by CPernet** [comment]
' it should go without saying.' is never a good idea IMO, always be explicit

**Comment by DimitriPapadopoulos** [comment]
Then I'd say that this agreement **has** prevalence. Otherwise, we end up implying that US extraterritorial laws have prevalence, which the GPRD precisely tries to avoid.

**Comment by DimitriPapadopoulos** [comment]
I agree with the intent that the agreement cannot override local data protection rules, or prevent from following stricter such rules. The new wording makes this intent clearer, thanks!
