### ISSUE TITLE
Typos in Ultimate Consent

### ISSUE THREAD

**Issue by ferreira-santos** [con/open-brain-consent#127]
While working on the Portuguese translation of the [Ultimate consent form](https://github.com/con/open-brain-consent/blob/master/docs/source/ultimate.rst) we noticed two typos in the original English document:
- on two instances the text reads "development of new methods for studying brain" where is should probably read "development of new methods for studying **the** brain".

**Comment by yarikoptic** [comment]
ha -- do we need a `@con/english` i18n team? ;)  I am not a native speaker so articles aren't my strongest -- can't say for sure if it would be applicable here (as the particular brain vs a brain of someone/in general).  

But, moreover, we have two instances in the ultimate without `the`, but with `the` in the GDPR version:
 
![image](https://user-images.githubusercontent.com/39889/161097617-f204564a-c4c3-4424-b685-b0d0b2111f29.png)

so clearly we need to unify. According to google searching ["studying brain"](https://www.google.com/search?q=%22studying+brain%22) is used whenever `studying brain SOMETHING` like `studying brain function` but indeed it should be   ["studying the brain"](https://www.google.com/search?q=%22studying+the+brain%22)

sending out PR to fix this, thanks @ferreira-santos !
