### ISSUE TITLE
Link for UGlasgow sample consent form outdated

### ISSUE THREAD

**Issue by yukaizou2015** [con/open-brain-consent#137]
Hello,

I found that link for UGlasgow sample consent form is outdated. Here's the updated link:

- [3T fMRI consent form v3.0](https://www.gla.ac.uk/media/Media_1071725_smxx.docx)

More consent forms can be found at https://www.gla.ac.uk/schools/psychologyneuroscience/research/ccni/ccniproj/

Best wishes,
Kai

**Comment by yarikoptic** [comment]
care to send a PR to fix that up so you were properly acknowledged as a contributor? ;)

**Comment by yukaizou2015** [comment]
Looks like `docs/_generated_git/samples_index.rst` needs to be re-generated using DataLad. I'll have a look how to do this as soon as possible.
