### ISSUE TITLE
Initiate "branding" and versioning of the ultimate consent form

### ISSUE THREAD

**Issue by yarikoptic** [con/open-brain-consent#27]
I think we should release current one as 1.0 and call it something like "OBC", so it becomes "OBC 1.0"

What do you think @chrisfilo ?

**Comment by chrisfilo** [comment]
Sounds good to me.

**Comment by yarikoptic** [comment]
Cool, so what about
`OBC[-2T]` for the name and `MINOR.MAJOR[.<LANG>[.<PATCH>]]`

where
- `-2T` for "two types" (public + restricted)
- `<LANG>` is the "language code" if translated from original (`en-US`?).  I guess we could/should use [IETF language tag](https://en.wikipedia.org/wiki/IETF_language_tag) (yet to find a full list, [rfc5646](https://tools.ietf.org/html/rfc5646) seems to be the most recent "Standard" description for it)
- `[.<LANG>[.<PATCH>]]` would depict version post `MINOR.MAJOR` for the revision of the translation

Example: OBC-2T 1.0.DE.2

- May be should be full `OBCF` (to include "Form") in the name?
- I don't like `-2T`.  Any better ideas? (`MIXED` is too long, may be `PP` for public+private?)
- First I have added `-<LANG>` to the name but didn't like duplication there and in the version spec.

**Comment by yarikoptic** [comment]
oh hoh, just spotted this issue which was duplicated in #42 (versions) and #45 (OBC branding).  In #42 I haven't thought about public/restricted. Let's continue on versioning in #42
