### ISSUE TITLE
Chrome auto-translates the Ultimate form on readthedocs.org

### ISSUE THREAD

**Issue by njvack** [con/open-brain-consent#29]
Hi folks,

I was looking at [the consent form on readthedocs.org](https://open-brain-consent.readthedocs.io/en/stable/ultimate.html), and noticed that the language was kind of weird and stilted. Finally, I realized that Chrome (69.0.3497.100 on MacOS 10.13.16) seems to think the page is in French had "helpfully" translated the English language version of the document... back to English... and changed the text significantly. For example:

> The data and samples from this study might be used for other, future research projects in addition to the study you are currently participating in. Those future projects can focus on any topic that might be unrelated to the goals of this study. We will give access to the data we are collecting, including the imaging data, to the general public via the Internet and a fully open database.

> The data we share with the general public will not have your name on it, only a code number, so people will not know your name or which data are yours. In addition, we will not share any other information that we think might help people who know you guess which data are yours.

becomes

> The data and samples from this study may be used for other studies. Those future projects can focus on any topic that might be unrelated to the goals of this study. We will give access to the data we are collecting, including the imaging data, to the general public via the Internet and a fully open database.

>The data we share with the general public will not have your name on it, only a code number, so do not know your name or your data. In addition, we will not share any other information that we think might help you.

I'm not sure where Chrome is getting its ideas about the language, or how we might tell people this is even a thing that can happen — but it definitely left me confused at first.

**Comment by yarikoptic** [comment]
This issue will be closed by #46 which would place translations into their dedicated files.
