### ISSUE TITLE
INCF recommendation is gone/moved?

### ISSUE THREAD

**Issue by yarikoptic** [con/open-brain-consent#31]
Brought up by @agt24 : url from https://open-brain-consent.readthedocs.io/en/stable/recommendations.html points to http://datasharing.incf.org/ni/Data_Sharing_Language_Recommendations for International Coordination Facility (INCF) Neuroimaging taskforce, and that one is gone now.
@dnkennedy @jbpoline -- do you know where it is now if anywhere?

**Comment by agt24** [comment]
bump @dnkennedy @jbpoline

**Comment by jbpoline** [comment]
@agt24  @yarikoptic I have sent an email to Mathew, hopefully we will get that sorted soon

**Comment by agt24** [comment]
Did you hear back from Mathew, @jbpoline ?

**Comment by jbpoline** [comment]
@agt24 : I did not - sorry - but I will have him on the phone Wednesday and will remind him - thanks for the ping

**Comment by vsoch** [comment]
@yarikoptic unrelated, but since I got a GitHub notification I wanted to share! Someone was mentioning a "git for data" and [I mentioned datalad](https://www.reddit.com/r/programming/comments/az9ygb/designing_git_for_data_im_thinking_of_creating_a/ei6gsk2/?context=3).

His [repos is here](https://github.com/Fiedzia/Git-for-data), it might be worth reaching out to see if datalad would be useful to him, or if not, what it's missing.

**Comment by yarikoptic** [comment]
thanks @vsoch , I followed up at https://github.com/Fiedzia/Git-for-data/issues/1 
Cheers!

**Comment by cfitz** [comment]
Hi,
Did some poking around about this datasharing.incf.org ( Sorry, this was way before my time! ) 
I found the content in the wayback machine:
https://web.archive.org/web/20150924131659/http://datasharing.incf.org/ni/Data_Sharing_Language_Recommendations

We do have a page about this at: https://www.incf.org/resources/data-repositories

Should I put in a PR to change the link to the incf.org  site?

**Comment by jbpoline** [comment]
yes - we would like to have that link work again - it may require a PR on
the Datalad side ?

**Comment by yarikoptic** [comment]
so you want to point to the web archive or the plain data-repositories?
yes - could be fixed by submitting PR against this repository

**Comment by cfitz** [comment]
Let me see about moving the content somewhere not in the archive.

**Comment by jbpoline** [comment]
thanks a lot
JB

**Comment by yarikoptic** [comment]
FYI: Perspective "fix" in #41 replaces INCF one (since nobody dug it out) with others.
