### ISSUE TITLE
move under the umbrella of "Center for Open Neuroscience" (github.com/con)

### ISSUE THREAD

**Issue by yarikoptic** [con/open-brain-consent#35]
Although originally placed under DataLad umbrella, this project was not really directly related to DataLad developments.  I am thinking to move it under [Center for Open Neuroscience](https://github.com/con) umbrella.  Any objections @mih @chrisgorgo et al?

**Comment by vsoch** [comment]
I'm just in amazement that you got the "con" GitHub alias. Three letters! wowza.

**Comment by chrisgorgo** [comment]
No objections.

That org alias has some negative CONnotation.
Ba Dum Tsss

Ok I will go now :)

**Comment by yarikoptic** [comment]
> I'm just in amazement that you got the "con" GitHub alias. Three letters! wowza.

GitHub support is great when it comes to re-claiming unused aliases. Got dbic as well just two days back ;-)

**Comment by yarikoptic** [comment]
> No objections. That org alias has some negative CONnotation. Ba Dum Tsss Ok I will go now :)

Everything does these days. Hacker, lad, fella... But we are to shape perceptions of the future.
People stopped thinking about bad connotation of git ;-)

And I just open my talks with "I am a CON man" ;-)

**Comment by yarikoptic** [comment]
I will assume that @mih doesn't mind

**Comment by mih** [comment]
Correct!

**Comment by yarikoptic** [comment]
done
