### ISSUE TITLE
add informed consent forms of Donders Centre for Cognitive Neuroimaging

### ISSUE THREAD

**Issue by robertoostenveld** [con/open-brain-consent#37]
I propose to add the informed consent forms of the Donders Centre for Cognitive Neuroimaging (DCCN). These have been designed to comply with the GDPR and are compatible with sharing data from healthy adult research participants on the [Donders Repository](https://data.donders.ru.nl/). Children and patients that volunteer as research participants at the DCCN are *not* covered by these.

The online PDFs can be found [here](https://www.ru.nl/donders/vm-site/proefpersonen/engelse-versies-centers/participants/donders-centre-cognitive-neuroimaging-en/); specifically you should have the "Technique specific information packages" in the right column. These include the info, screening and consent forms and are sent to the research participants at least 24 hours prior to the experiment. The General information brochure would be good to add as well (see link in the main text on that page). 

Please note that the DCCN is part of the Donders Institute for Brain, Cognition and Behaviour - which is again part of the Radboud University. Other centers of the Donders Institute fall under other faculties, hence procedures and ethics regulations are (slightly) different. It should therefore be listed as "Donders Centre for Cognitive Neuroimaging" - not as the "Donders Institute". On [this page](https://www.ru.nl/donders/vm-site/proefpersonen/engelse-versies-centers/participants/) at the bottom are also links to two other centers that are part of the Donders Institute, but I personally do not know the details of those.

PS If I would know how git annex would work, I would have sent this as a pull request.

**Comment by yarikoptic** [comment]
I lost myself in open browser windows etc..

added for MRI and EEG as of 0.2.5, should be reachable from https://open-brain-consent.readthedocs.io/en/stable/samples.html  now

re git-annex, please see https://github.com/con/open-brain-consent/pull/23#discussion_r198577354 , but may be I should reconsider and we could establish some nice workflow for that

**Comment by yarikoptic** [comment]
ah -- and -- THANKS!
