### ISSUE TITLE
Split translations into separate files

### ISSUE THREAD

**Issue by yarikoptic** [con/open-brain-consent#43]
ATM they are all piled up in a single file.
That complicates their management and/or in the future comparison between versions (see #42 ).  So we should keep only canonical version in the top level file and then reference all translations in the individual files.  Ideally uniform names such as `<base>.<language>.<ext>` where language comes from https://www.w3schools.com/tags/ref_language_codes.asp, so instead of

https://open-brain-consent.readthedocs.io/en/stable/ultimate.html#spanish

get 

https://open-brain-consent.readthedocs.io/en/stable/ultimate.es.html

or smth alike

**Comment by vborghe** [comment]
I'd like to help but I'm a newbie. 

Would something like this work? https://github.com/vborghe/open-brain-consent/tree/master/docs/source/gdpr i.e., only English on the main page, then links to the other ones (full name could be replaced by language code)

If so, I could do it for all languages for both _ultimate_ and _gdpr_

**Comment by yarikoptic** [comment]
Great start! Could you follow naming I suggested in https://github.com/con/open-brain-consent/issues/42#issuecomment-622492727, which I should have actually posted here

**Comment by vborghe** [comment]
Sounds good! I tried to follow the structure:
```
i18n/ultimate.fr.rst
i18n/ultimate.es.rst
...
gdpr/i18n/ultimate_gdpr.fr.rst
gdpr/i18n/ultimate_gdpr.es.rst
....
```
How does this look?
https://github.com/vborghe/open-brain-consent/tree/master/docs/source

**Comment by yarikoptic** [comment]
Sorry, missed. Yet to look into files but naming looks good. @CPernet also says that it is "done" - I hope that you two didn't duplicate the effort

**Comment by yarikoptic** [comment]
Again - sorry that I have missed the comment... ideally there should have been a PR for those changes to be able to review them and also may be it would have helped me to spot this WiP.

**Comment by CPernet** [comment]
looks like  we both done it  -- opportunity to merge and see if we use the same language ISO

**Comment by vborghe** [comment]
My bad, sorry! I'm still getting the hang of GitHub (and its practices). Happy to proceed as you deem best.

**Comment by yarikoptic** [comment]
ok, let's continue in #46 which will close this issue
