### ISSUE TITLE
Obscure wording in the GDPR edition

### ISSUE THREAD

**Issue by mhavu** [con/open-brain-consent#51]
The wording in [More information about your rights when processing data](https://github.com/con/open-brain-consent/blob/master/docs/source/gdpr/ultimate_gdpr.rst#more-information-about-your-rights-when-processing-data) implies that it is the participant who processes the data. This could be remedied, for example, by changing *"your rights when processing your personal data"* to *"your rights **regarding the processing of** your personal data"* or *"your rights when your personal data **is processed**"*.

**Comment by yarikoptic** [comment]
Indeed. Either suggested version is good with me. PR?  Attn @con/gdpr

**Comment by yarikoptic** [comment]
Note: When changing for meaning like this, which might need translations adjustment, the minor version component would need a boost, or to 1.1.0 version in the file

**Comment by CPernet** [comment]
if we change English - we should then push an issue for i18 team as to have all other translations adjusted as well ; kind of the problem with that many but we could also have a warning that English is ahead ??

**Comment by mhavu** [comment]
Most localisations should not require more than a bump in the version number. In my opinion, this could be combined with notifying the i18n team of what is to be included in the localised versions of OBC-GDPR-ULT and OBC-GDPR-DUA: currently the localised versions of OBC-GDPR-ULT seem to include the *Instructions* chapter without the chapter heading, whereas the localised versions of OBC-GDPR-DUA do not include the *General considerations for a Data User Agreement* chapter or the introductory text. In case these are to be translated, the version number should not be touched without also including the missing translations.

(As a side note, the contents of `data_user_agreement.nl.rst` seem to be Turkish, not Dutch.)

**Comment by yarikoptic** [comment]
> (As a side note, the contents of `data_user_agreement.nl.rst` seem to be Turkish, not Dutch.)

crap -- might have been the bug I introduced when trying to merge multiple splitting efforts...

NB better to submit such issues separately so they do not get swallowed within other issues ;)

**Comment by yarikoptic** [comment]
> > (As a side note, the contents of `data_user_agreement.nl.rst` seem to be Turkish, not Dutch.)
> crap -- might have been the bug I introduced when trying to merge multiple splitting efforts...

nope - it was added as such in 31ca1d663155157dc35ea64b409e266686adf121 so @CPernet might know where to get the original translation

<details>
<summary>indeed - there is no diff between .nl and .tr ;)</summary> 

```shell
$> diff data_user_agreement.nl.rst data_user_agreement.tr.rst
1c1
< .. _chap_dua_nl:
---
> .. _chap_dua_tr:
3,5c3,5
< Dutch
< -----
< (translation courtesy of Dr Patricia Clement and Dr Henk-Jan Mutsaerts)
---
> Turkish
> -------
> (translation courtesy of Dr. Esin Öztürk Işık)
8c8
< ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
---
> ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
10c10
< **Version:** OBC-GDPR-DUA.nl 1.0.0
---
> **Version:** OBC-GDPR-DUA.tr 1.0.0

```
</details>

**Comment by mhavu** [comment]
> NB better to submit such issues separately so they do not get swallowed within other issues ;)

Indeed. I just figured this would be blatantly obvious to the maintainers of the Dutch localisation when they check those other things.

**Comment by CPernet** [comment]
pulling the old 'one file' and copy/paste over -- pulling the update from my fork and doing a PR -- re dutch fixing

**Comment by CPernet** [comment]
re english fixing -- noting against it but in this case we should submit the change in i18 so others also make changes in translations (otherwise it is becoming too divergent)

**Comment by mhavu** [comment]
@CPernet What about the scope of the translation? Should the instructions in the beginning of the files also be included?

**Comment by yarikoptic** [comment]
I think we don't need to translate them. They send to be not participant oriented really. So let's just decide on fixing wording: after fixed in English, we need to initiate changelog probably per each of translatable versions items, list it there and contact i18n teams to adjust corresponding translations. Might take awhile so I would release without waiting for that. With a changelog and version disparity users might see it and fix it up when used and possibly even submit corrections

**Comment by mhavu** [comment]
> I think we don't need to translate them. They seems to be not participant oriented really. 

In that case I would also remove the _Instructions_ chapter (first paragraph) from OBC-GDPR-ULT.

**Comment by yarikoptic** [comment]
ok, let's continue on this specific issue in https://github.com/con/open-brain-consent/issues/56 . I would not make it a blocker for the release though.  The initial issue on wording - we better at least decide before release on what we do with it
