### ISSUE TITLE
Update Zenodo

### ISSUE THREAD

**Issue by cMadan** [con/open-brain-consent#97]
It looks like Zenodo has v0.2.4, as of Sept 9 2019, whereas the project has been updated quite a bit since then. It would be great if the Zenodo archive can be updated to the current version.

**Comment by yarikoptic** [comment]
THANK YOU and sorry for the delay.  I have tried to figure out why zenodo skipped 1.0.0 release but it is impossible AFAIK... so I just created a new release 1.1.0 and all seems to be well with that one https://doi.org/10.5281/zenodo.4264941  . So, we will not have a zenodo entry for 1.0.0 but at least would have 1.1.0 hopefully that is ok going forward.
